services:
  # Base de données
  mongo:
    image: mongo:6.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  # Système de Cache
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  # Backend (Node.js API)
  node-app:
    container_name: node-app-container
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/football
      - REDIS_URL=redis://redis:6379
      - PORT=4000
    depends_on:
      - mongo
      - redis
    restart: always

  # Frontend (React) + Nginx Reverse Proxy
  nginx:
    container_name: nginx-proxy-container
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - node-app
    restart: always

volumes:
  mongo-data: